### DISCUSSION TITLE
Stopping a running workload or triggering its failed condition

### DISCUSSION THREAD

**Discussion by mrogonna** [eclipse-ankaios/ankaios#240] [Q&A] [answered]
Hey guys,
My observation so far(correct me if i'm wrong):
1.  you can only add a new workload or delete any workload over CLI, no option to temporary stop/start or trigger failed condition for the workload
2. if you start an agent, it automatically starts all the workloads under that particular agent unless there are some inter-workload dependencies that needs to be met

Question:
1. how can I trigger a failed condition (exit with non-zero return code) for a workload to fulfil one of the inter-workload dependencies, ExecutionState(Failed(ExecFailed)) => AddCondition(ADD_COND_FAILED)
2. for debugging purposes, how can I manually stop/start a single running workload over cli?
3. is there a reset key? if yes, how can I reset the program to start from my initial startup configurations?

thank you for the help.

**Comment by windsource** [comment]
Hi @mrogonna,

the following Ankaios manifest shows how to trigger a workload based on failed workload:

```yaml
apiVersion: v0.1
workloads:
  willfail:
    runtime: podman
    agent: agent_A
    runtimeConfig: |
      image: docker.io/busybox:latest
      commandArgs: ["sh", "-c", "exit 1"]
  onfail:
    runtime: podman
    agent: agent_A
    dependencies:
      willfail: ADD_COND_FAILED
    runtimeConfig: |
      image: docker.io/busybox:latest
      commandArgs: ["sh", "-c", "echo 'I have been triggered.'"]
```

Save this to a file `example.yaml` and then call `ank apply example.yaml`.

For debugging purpose you can use `ank apply FILENAME` to start workloads and `ank apply -d FILENAME` to delete workloads.

The startup configuration is only applied at startup. So if you have a running Ankaios cluster and want to start a clean setup, perform the following steps:

1. Delete all running workloads using `ank delete <list of all workloads>`
2. Stop Ankaios agent by `sudo systemctl stop ank-agent`
3. Stop Ankaios server by `sudo systemctl stop ank-server`
4. Change the startup config
5. Start server and agent again
