### ISSUE TITLE
List agents

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#155]
## Description

Currently there is not CLI command to list the agents that are connected to the server. This is required to quickly see if all agents could connect to the server and are available to run workloads.

## Goals

Add a command `ank get agents` to list all agents.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by inf17101** [comment]
```shell
> ank get agents
agent_A
agent_B
agent_C
```

or

with a table structure showing the assigned workloads of the complete state (the server can take this from the desired state because it maintains the desired state, where "assigned workloads" means that the workloads are only assigned but not that the agent has processed them already or that they are running or something else, just to show the user some distribution)

```shell
AGENT NAME    ASSIGNED WORKLOADS
agent_A             3
agent_B             2
agent_C             0
```

**Comment by inf17101** [comment]
Do we need a table output like "kubectl get nodes" outputs:

```shell
> kubectl get nodes

NAME       STATUS   ROLES    AGE     VERSION
node-1     Ready    <none>   7d      v1.21.3
node-2     Ready    <none>   7d      v1.21.3
node-3     Ready    <none>   7d      v1.21.3
```

and to fill the table output with Ankaios related data:

```shell
> ank get agents

AGENT NAME   ASSIGNED WORKLOADS
agent_A            3
agent_B            0
agent_C            1
```
"ASSIGNED WORKLOADS" means that the workloads are just assigned in the desired state to those agents, it means not that the workloads are already handled by those agents. The server already has this information about the assigned workloads as it maintains the `CompleteState` internally.

or do you had something in mind without a table output and just simple listed agent names like this:

```shell
> ank get agents

agent_A
agent_B
agentC
```

Next I had a discussion with @krucod3 and we think both that it would be also useful to have the "list agents" feature for a workload, too. Meaning, a workload can request the agent list over the control interface to check which agents are available.

The agents can be listed inside the `CompleteState`, then we do not need a new message struct just for the CLI and it is usable over the control interface together with the authorization feature.

New example `CompleteState`:

```yaml
desiredState:
  apiVersion: v0.1
  workloads:
    hello1:
      agent: agent_A
      tags: []
      dependencies:
        filesystem_init: ADD_COND_SUCCEEDED
      restartPolicy: NEVER
      runtime: podman
      runtimeConfig: |
        image: alpine:latest
        commandOptions: [ "--rm"]
        commandArgs: [ "echo", "Hello Ankaios"]
    hello2:
      agent: agent_B
      tags:
      - key: owner
        value: Ankaios team
      dependencies: {}
      restartPolicy: ON_FAILURE
      runtime: podman
      runtimeConfig: |
        image: alpine:latest
        commandOptions: [ "--entrypoint", "/bin/sh" ]
        commandArgs: [ "-c", "echo 'Restarted on failure.'; sleep 2"]
    nginx:
      agent: agent_B
      tags:
      - key: owner
        value: Ankaios team
      dependencies: {}
      restartPolicy: ON_FAILURE
      runtime: podman
      runtimeConfig: |
        image: docker.io/nginx:latest
        commandOptions: ["-p", "8081:80"]
workloadStates:
  agent_A:
    hello1:
      9f4dce2c90669cdcbd2ef8eddb4e38d6238abf721bbebffd820121ce1633f705:
        state: Pending
        subState: WaitingToStart
        additionalInfo: ''
  agent_B:
    hello2:
      50dfcc07f50a94f113f33fe1329eeebce93d134176d90b9a8ef3c2cfa15d1a7b:
        state: Succeeded
        subState: Ok
        additionalInfo: ''
    nginx:
      7d6ea2b79cea1e401beee1553a9d3d7b5bcbb37f1cfdb60db1fbbcaa140eb17d:
        state: Running
        subState: Ok
        additionalInfo: ''
agents:
  agent_A: {}
  agent_B: {}
```
