### ISSUE TITLE
Not possible to create a new release

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#166]
When creating a new release the Github Action does not start.

The `release` workflow does not start with the error message:

```
Canceling since a deadlock for concurrency group 'Release-refs/tags/v0.4.0' was detected between 'top level workflow' and 'build'
```

## Current Behavior
The release workflow does not start.

## Expected Behavior
When creating a new release the release workflow should start.

## Steps to Reproduce

1. Goto [Releases](https://github.com/eclipse-ankaios/ankaios/releases)
2. Select `Draft a new release`
3. Click `Choose a tag` and enter a new tag name
4. Enter any title
5. Click publish release

Check the actions.

## Logs

See above and also in https://github.com/windsource/ankaios/actions/runs/7669961576.

## Additional Information

I think this is related to the conccurency settings we use the in workflows.

## Final result

**To be filled by the one closing the issue.**

**Comment by koppor** [comment]
Oh, wow 😅

Quick checks:

1. In "my" project, I do have the same concurrency group - and I can do releases (https://github.com/JabRef/jabref/blob/main/.github/workflows/deployment.yml)

2. I did not see the error message at the above link. Can you guide me, where to click?

![image](https://github.com/eclipse-ankaios/ankaios/assets/1366654/454f60b4-f6f8-4055-b3b2-89c07e54b6af)

**Comment by koppor** [comment]
OK, I see it

```yaml
jobs:
  build:
    uses: ./.github/workflows/build.yml
  documentation:
    permissions: write-all
    uses: ./.github/workflows/documentation.yml
```

With that, "build" is triggered.

Build is also triggered on push

```yaml
  push:
    branches:
      - main
```

That could be the conflict.

Investigating...
