### ISSUE TITLE
Unify error handling for missing fields in Ankaios manifests

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#194]
When you start the start `ank-server` and pass a startup config which is missing the `runtime` field, `ank-server` exists and logs an error:

```
[2024-02-27T12:35:00Z ERROR] Parsing start config failed with error: 'workloads.databroker: missing field `runtime` at line 4 column 5'
```

When you call `ank set state -f databroker.yaml desiredState.workloads` again without a `runtime` field the CLI does not print any error. Obviously the parsing worked fine. Finally the agent logs an error about the missing `runtime`.

A first analysis showed that different structures are used for parsing: `StoredWorkloadSpec` vs. `WorkloadSpec`. While the first does not use default values, the second provides defaults (empty string for strings I assume) and thus does not complain about missing `runtime` field.

## Current Behavior

The result of parsing Ankaios manifests is different when parsed as saved state or desired state.

## Expected Behavior

An Ankaios manifest shall always be parsed in the same way, independent of using as startup config or when used with `ank set state` or `ank apply`. We should decide which fields are mandatory (`runtime` should be one of them) and then the parser should complain when those fields are not present and reject the workload.

## Steps to Reproduce

Call `ank-server -c myworkload.yaml` with `myworkload.yaml` being 

```
workloads:
  myworkload:
    # runtime: podman
    agent: agent_A
    restart: true
    runtimeConfig: |
      image: docker.io/nginx:latest
```

With a running server call `ank set state -f myworkload.yaml desiredState.workloads`  with `myworkload.yaml` being

```
formatVersion:
  version: v0.1
startupState:
  workloads: {}
desiredState:
  workloads:
    myworkload:
       # runtime: podman
      agent: agent_A
      restart: true
      runtimeConfig: |
        image: docker.io/nginx:latest
workloadStates: []
```

## Final result
The issue has been fixed in the #191 and #189. The pull request #205 adds forgotten requirements coverage.
