### ISSUE TITLE
Startup config does not check `apiVersion`

### ISSUE THREAD

**Issue by maturar** [eclipse-ankaios/ankaios#208]
The ticket #193 has implemented new mandatory item in the startupConfig `apiVersion`. The Ankaios shall check if the `apiVersion` is available in the startupConfig and if the version matches to the version expected by the Ankaios.

## Current Behavior

The Ankaios only checks wheter the item is present or not. The Ankaios does not check if the version matches.

## Expected Behavior

The Ankaios shall check if the `apiVersion` in the startupConfig matches and reject the startupConfig without valid `apiVersion`.
To be discussed with the team: what to do when the version does not match? Stop the server (so the server does not run anymore)? Or start the server without config?

## Steps to Reproduce

Create `brokenStartConfig.yaml` with following content:

```yaml
apiVersion: invalidVersion
workloads:
  hello1:
    runtime: podman
    agent: agent_B
    restart: true
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      image: alpine:latest
      commandOptions: [ "--rm"]
      commandArgs: [ "echo", "Hello Ankaios"]
  hello2:
    runtime: podman
    agent: agent_B
    restart: true
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      image: alpine:latest
      commandArgs: [ "echo", "Hello Ankaios"]
```

* Start the server with the config: `./ank-server -c brokenStartConfig.yaml`
* The server reads config and starts, but the server shall reject the config instead.

## Final result
The server checks if the `apiVersion` in the startupConfig matches to the expected version and stops if the version does not match.
