### ISSUE TITLE
Change the restart flag to a restart policy enum

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#212]
## Description

This issue handles only the interface changes needed for #5 

## Goals

Define the new restart policy interface.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by krucod3** [comment]
According to the changes in the PR, a config would not look like this:
``` yaml
workloads:
  nginx:
    agent: agent_A
    restart: ALWAYS
    runtime: podman
    runtimeConfig: |
      image: docker.io/nginx:latest
      commandOptions: ["-p", "8081:80"]
```

Where `restart` could be one of [`ALWAYS`, `NEVER`, `ON_FAILURE`]
