### ISSUE TITLE
ank apply does not return when empty agent is provided

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#241]
ank apply does not return when a manifest with an empty agent is provided.

## Current Behavior

`ank apply -d` blocks and shows

```
❯ ank apply nginx_empty.yaml
 WORKLOAD NAME   AGENT   RUNTIME     EXECUTION STATE   ADDITIONAL INFO
 nginx1                  podman    / NotScheduled
```

## Expected Behavior
`ank apply` shall return and show the the workload is in state `NotScheduled`.

## Steps to Reproduce

1. Create a file `nginx_empty.yaml`:
  ```
  apiVersion: v0.1
  workloads:
    nginx1:
      runtime: podman
      agent: ""
      runtimeConfig: |
        image: docker.io/nginx:latest
  ```
2.  Call `ank apply nginx_empty.yaml`.

## Context (Environment)

Anakios v0.3.0

## Final result

**To be filled by the one closing the issue.**
