### ISSUE TITLE
Add Control Interface access for `podman-kube` workloads

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#256]
## Description

Currently `podman-kube` workloads do not have access to the Control Interface. The background is that the interface needs to be mounted in a specific container belonging to a pod. The `podman-kube` runtime allows multiple pods to be specified for the same workload and each could have multiple containers inside. This means that an explicit configuration is required s.t. Ankaios can mount the Control Interface pipes at the correct, expected place.

An initial concept how the location can be specified was already done here: https://github.com/eclipse-ankaios/ankaios/issues/172#issuecomment-2066627960

## Goals

Add Control Interface access to podman-kube.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by krucod3** [comment]
```yaml
apiVersion: v0.1
workloads:
  hello-pod:
    runtime: podman-kube
    agent: agent_B
    restartPolicy: NEVER
    controlInterfaceAccess:
      targetPath: "nginx-pod/nginx-container"
      allowRules:
      - type: StateRule
        operation: Read
        filterMask:
        - desiredState
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      manifest: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: hello-pod
        spec:
          restartPolicy: Never
          containers:
          - name: looper
            image: alpine:latest
            command:
            - sleep
            - 50000
          - name: greater
            image: alpine:latest
            command:
            - echo
            - "Hello from a container in a pod"
        ---
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: nginx-config
        data:
          nginx.conf: |
            {{> indent content=nginx_conf}}
        ---
        apiVersion: v1
        kind: Pod
        metadata:
          name: nginx-pod
        spec:
          restartPolicy: Never
          containers:
          - name: nginx-container
            image: docker.io/nginx:latest
            ports:
            - containerPort: 80
              hostPort: 8080
            volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: control-interface-volume # Has to be added by us
              mountPath: /run/ankaios/control_interface # Has to be added by us
          volumes:
          - name: nginx-config-volume
            configMap:
              name: nginx-config
          - name: control-interface-volume # Has to be added by us
            hostPath:
              path: /tmp/ankaios/<agent name>.io/<workload instance name>/control-interface/
              type: Directory # this field is optional
```

TBD: 
* name: check if `targetPath` is OK
* separator must be a char not usable in the pod and container names. Slash should be fine, but must be checked
