### ISSUE TITLE
Ank apply does not detect deleted workloads during it runs

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#276]
If the `ank apply` command applies a workload and during the workload is deleted during the apply, then the table output of `ank apply` shows the workload with workload state `Removed`, but it hangs and the spinner is still running.

## Current Behavior

Ank apply hangs when it runs and a workload it touches is deleted.

## Expected Behavior

The Ank apply command shall not hang and return if the workload it touches was deleted.

## Steps to Reproduce

The situation can be easily reproduced with forcing retries when initially starting a workload, because then there is enough time for a human to enter the delete command during the ank apply runs. Of course, the bug can also be reproduced without using the retry feature but with scripting.

1. Start the Ankaios server: `./ank-server`
2. Start the Ankaios agent: `./ank-agent --name agent_A`
3. Apply the manifest `invalidworkload.yml` mentioned below: `./ank apply invalidworkload.yml`
4. Start a second shell and enter a delete of the workload inside the manifest: `./ank delete workload invalidworkload`
5. Switch back to the ank apply terminal window and you will see that the ank apply command still runs and stucks but the workload has already the workload state `Removed` because of the delete request in the other shell.

## Context (Environment)

All supported platforms are affected, but detected with: Linux amd64 (64 bit)
Ank apply CLI command

## Logs

Hanging ank apply screenshot:
![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/a2108643-d398-42ab-941f-f790255ad28d)

## Additional Information

```yaml
# invalidworkload.yml
apiVersion: v0.1
workloads:
  invalidworkload:
    runtime: podman
    agent: agent_A
    runtimeConfig: |
      image: docker.io/busybox:latest
      commandOptions: ["--invalidoption"]
```

## Final result

**To be filled by the one closing the issue.**
