### ISSUE TITLE
Quickstart manual is outdated

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#398]
The [Quickstart section in the documentation](https://eclipse-ankaios.github.io/ankaios/main/usage/quickstart/) is outdated. A complete state is shown with a part:

```
workloadStates:
- instanceName:
    agentName: agent_A
    workloadName: nginx
    id: 7d6ea2b79cea1e401beee1553a9d3d7b5bcbb37f1cfdb60db1fbbcaa140eb17d
  executionState:
    state: Running
    subState: Ok
    additionalInfo: ''
```

The format has changed and also the new config structure is not part of it.

## Current Behavior

See above.

## Expected Behavior

Update the Qucikstart section such it reflects the v0.5.0 version.

## Steps to Reproduce

Read https://eclipse-ankaios.github.io/ankaios/main/usage/quickstart/.

## Final result

**To be filled by the one closing the issue.**
