### ISSUE TITLE
Add restart handling

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#5]
## Description

The state contains a boolean field `restart` which is currently ignored. The restart handling should be implemented.

## Goals

- Define if  a simple boolean flag is sufficient or if we need a something like `always`, `never`and `on failure`
- When restart is set the the agent shall restart a workload when it was stopped for any reason like failure or system restart

## Tasks

tbd.

**Comment by krucod3** [comment]
Decisions after discussion:
* the restart bool flag will be removed and supplemented with a restart policy enum with the fields mentioned above
* default value for the restart flag is `never`
* the difference between `always` and `failure` is the exit code of the workload
* all workloads will be started again when the agent is started (unless they are already running), because a newly started agent is treated as a restart of the node. Already running workloads will not be restarted in this case. This is independent from the restart policy of the workload.

**Comment by krucod3** [comment]
After discussions and because of the bug ticket #158: most important here is that the restart of Ankaios starts the workloads again .

**Comment by inf17101** [comment]
I have done some research again, just to check how the restart flags vary between all the known software orchestrators.

Kubernetes supports `Never`, `Always`, `OnFailure` (https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/). K3s and docker-compose supports the same values. But docker-compose (https://docs.docker.com/config/containers/start-containers-automatically/) supports one more interesting field called `unless-stopped`. The `unless-stopped` restart policy restarts a workload in the same way like `always` does besides the user has actively stopped the workload. For transferring into automotive use cases maybe someone wants to configure that a workload shall be restarted when it is failed or what else, but if an integrator stops the workload the orchestrator shall not restart it (because it is unnecessary since the user's decision was actively to see the workload not running anymore).

**Comment by krucod3** [comment]
I was also thinking about a max retries value for the on-failure case. We need to think if we would go with a value for the enum or a separate attribute. As for the unless-stopped, for Ankaios this would be the normal case as we either delete or assign to the "" agent which cannot restart anything.

**Comment by inf17101** [comment]
Proposal for an Ankaios manifest containing the restart policy enum flags:

```yaml
apiVersion: v0.1
workloads:
  restarted_always:
    runtime: podman
    agent: agent_A
    restart: ALWAYS
    runtimeConfig: |
      image: alpine:latest
      commandOptions: [ "--entrypoint", "/bin/sh" ]
      commandArgs: [ "-c", "echo 'Always restarted.'; sleep 10"]
  restarted_never:
    runtime: podman
    agent: agent_A
    restart: NEVER
    runtimeConfig: |
      image: alpine:latest
      commandArgs: [ "echo", "Explicitly never restarted."]
  default_restarted_never: # default restart value = NEVER
    runtime: podman
    agent: agent_A
    runtimeConfig: |
      image: alpine:latest
      commandArgs: [ "echo", "Implicitly never restarted."]
  restarted_on_failure:
    runtime: podman
    agent: agent_A
    restart: ON_FAILURE
    runtimeConfig: |
      image: alpine:latest
      commandOptions: [ "--entrypoint", "/bin/sh" ]
      commandArgs: [ "-c", "echo 'Restarted on failure.'; sleep 7; exit 1"]
```

The default value is "never" and used when the user does not specify the restart flag.

Three different restart policies:

- __never__: Ankaios does never restart the workload. If the Ankaios agent is restarted, the workload is resumed by the agent.
- __always__: Ankaios restarts the workload if the runtime reports that the workload has finished regardless of the exit code. If the Ankaios agent is restarted, the workload is restarted if it is not running.
- __on_failure__: Ankaios restarts the workload if the runtime reports that the workload has exited with exit code != 0. If the Ankaios agent is restarted and the agent detects that the workload has failed, the workload is restarted.
