### ISSUE TITLE
Use cargo-deny for license checks

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#59]
## Description

Currently the license of the dependencies is only manually checked.

## Goals

Use [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) to check the license of dependencies with every build and break the build when a dependency does not comply to the license we use.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Add cargo-deny to the dev container
- [x] Create config `deny.toml`
- [x] Add to CI build

**Comment by windsource** [comment]
A first draft for `deny.toml`:

```toml
# Config file for cargo deny
# For all options see https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
]
private = { ignore = true }
exceptions = [{ name = "unicode-ident", allow = ["Unicode-DFS-2016"] }]
copyleft = "deny"

[bans]
multiple-versions = "allow"

[advisories]
vulnerability = "warn"
```
