### ISSUE TITLE
Configure self service with initial branch protection rules

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#71]
## Description

After we have enabled the selfservice via Gitlab Issue https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3805 and now trying to make strict branch protection rule for main branch, I have noticed that the workflow event triggering setting of the documentation wokflow (https://github.com/eclipse-ankaios/ankaios/blob/main/.github/workflows/documentation.yml) makes some trouble.

The problem is caused by the path-filter and branch-filter setting inside this workflow:

```
on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
      - 'api/proto/**'
      - '.github/workflows/documentation.yml'
  pull_request:
    paths:
      - 'doc/**'
      - 'api/proto/**'
      - '.github/workflows/documentation.yml'
```

If I configure the workflow as a required status check, then a PR is even blocked for merging if the PR does not change any of the files in the path-filter setting of the documentation workflow. The workflow is marked as pending and the PR is not allowed to be merged.

![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/08db66ba-2e01-49ce-a4b1-c255353386eb)

## Goals

Solve the problem, so that the documentation workflow runs and blocks the PR from merging if a doc file in the file-path setting was changed by a PR but also does not block other PRs from merging that are not changing any doc file.

### Summary

The self service was enabled with initial branch protection rules. Now, nobody can merge on main without a PR and status checks are required.

To fix the documentation workflow the workflow trigger condition was removed and integrated into a job conditional (because a skipped job does not mark a workflow as pending or not started). To fix this an additional job is created inside the documentation workflow that checks with a "path filter" GH action whether the documentation must be build or not in the pipeline. This prevents, that PRs are blocked when the documentation workflow is marked as required status check in the branch protection rules.

### Tasks

- [x] Figure out how the self service works
- [x] Configure branch protection rules
- [x] Extend the user documentation about the self service (links to self service documentation and general infos are enough)
